logging:
    level:
        com:
            dxc: TRACE

cxf:
    path: /rest
jbpm:
    executor:
        enabled: false
kieserver:
    dmn:
        enabled: true
    drools:
        enabled: true
    jbpm:
        enabled: true
    jbpmui:
        enabled: true
    location: http://localhost:8090/rest/server
    serverId: myserviceapp
    serverName: myserviceapp
    swagger:
        enabled: true
server:
    address: 0.0.0.0
    port: 8090
spring:
    h2:
      console:
        enabled: true
    banner:
        location: classpath:banner.txt
    datasource:
        driver-class-name: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:spring-boot-jbpm
        username: sa
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                hbm2ddl:
                    auto: update
                show_sql: false
    jta:
        narayana:
            transaction-manager-id: 1
